[package]
name = "kvs"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
rocket_db_pools = { version = "0.1.0", optional = true }
rocket_dyn_templates = { version = "0.1.0", optional = true }
